# GitHub Pages configuration for PR previews
# This file ensures PR previews work correctly with Hugo

# Enable GitHub Pages
# This is automatically handled by GitHub Actions, but this file documents the setup

# PR previews will be available at:
# https://reliant-labs.github.io/reliant-docs/ (main branch)
# https://reliant-labs.github.io/reliant-docs/ (PR previews with unique URLs)

# The preview workflow (.github/workflows/preview.yml) handles:
# - Building Hugo site for PRs
# - Deploying to GitHub Pages preview environment
# - Adding preview links to PR comments
# - Automatic cleanup when PRs are closed/merged

# No additional configuration needed here - GitHub Actions handles everything!
